AmzWholeSaleWeb/AmzWholeSaleWeb/Controllers/AmzHomeController.cs
using AmzBL.Products;
using AmzModel;
using Kendo.Mvc.Examples.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using log4net;
using Simplex.Tools.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Web.SessionState;
using AmzBL.Sections;

namespace AmzWholeSaleWeb.Controllers
{
    public class AmzHomeController : Controller
    {
        private static readonly ILog logger = LogManager.GetLogger(typeof(AmzHomeController));
        private AmzProductHandler productHandler;

        public AmzHomeController()
        {
            productHandler = new AmzProductHandler();
        }

        #region AMZ Specific
        public ActionResult Index()
        {
            logger.Info("AMZWholeSale Index()");
            string currentUser = System.Web.HttpContext.Current.Request.LogonUserIdentity.Name;
            logger.InfoFormat("System.Web.HttpContext.Current.Request.LogonUserIdentity.Name {0}", currentUser);
            currentUser = User.Identity.GetUserId();
            logger.InfoFormat("User.Identity.GetUserId() {0}", currentUser);
            currentUser = System.Security.Principal.WindowsIdentity.GetCurrent().Name.ToString();
            logger.InfoFormat("System.Security.Principal.WindowsIdentity.GetCurrent().Name.ToString() {0}", currentUser);
            currentUser = System.Web.HttpContext.Current.Session.SessionID;
            logger.InfoFormat("System.Web.HttpContext.Current.Session.SessionID", currentUser);

            return View(productHandler.GetProducts());


        }

   


        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult About()
        {

            return View();
        }

        public ActionResult Products_Read([DataSourceRequest] DataSourceRequest request, string productFilter, string productSection)
        {

            if (string.IsNullOrEmpty(productSection))
            {
                productSection = "Prime";
            }



            if (!string.IsNullOrEmpty(productFilter) && productFilter.Equals("Search products"))
            {
                productFilter = null;
            }

            var result = productHandler.GetProducts(productFilter, productSection);
            if (result == null || !result.Any())
                return RedirectToAction("ProductNotFound", "Shared", new { area = "" });
            else
                return Json(result.ToDataSourceResult(request));
        }
        #endregion




        











    }
}

AmzWholeSaleWeb/AmzWholeSaleWeb/Controllers/ProductAdminController.cs
using AmzBL.Products;
using AmzBL.Sections;
using AmzModel;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using log4net;
using Simplex.Tools.AppSettings;
using Simplex.Tools.Cart;
using Simplex.Tools.File;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace AmzWholeSaleWeb.Controllers
{

    public class ProductAdminController : Controller
    {
        public string FILE_UPLOAD_SUCCESSFUL = "File upload successful";
        public string PRODUCT_UPLOAD_SUCCESSFUL = "Product upload successful";
        private static readonly ILog logger = LogManager.GetLogger(typeof(ProductAdminController));

        private AmzProductHandler productHandler;
        private SectionDataHandler sectionHandler;

        public ProductAdminController()
        {
            productHandler = new AmzProductHandler();
            //sectionHandler = new SectionDataHandler();
        }

        #region Views
        // GET: ProductAdmin

        public ActionResult Index(string message, bool errorFund=false)
        {

            if(!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            string homeController = AppSettingsHandler.GetAppSettingsValue("HomeController");

            if (!User.IsInRole("AmzAdmin"))
            {
                return RedirectToAction("Index", homeController);
            }

            if (string.IsNullOrEmpty(message))
            {
                ViewBag.Message = "Upload new products.";
            }
            else
            {
                if(message.Equals(FILE_UPLOAD_SUCCESSFUL))
                    ViewBag.ErrorFound = false;
                else
                    ViewBag.ErrorFound = true;


                ViewBag.Message = message;
            }

            

            return View();
        }

        public ActionResult ManageProduct(string message, bool errorFund = false)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            //ViewData["SourceList"] = new string[] { "select...", "Furnituer", "Home", "Construction" }.Select(x =>
            //new
            //{
            //    Id = x,
            //    Status = x
            //});
            PopulateSections();

            if (string.IsNullOrEmpty(message))
            {
                ViewBag.Message = "Manage existing products.";
            }
            else
            {
                if (message.Equals(FILE_UPLOAD_SUCCESSFUL))
                    ViewBag.ErrorFound = false;
                else
                    ViewBag.ErrorFound = true;


                ViewBag.Message = message;
            }

            return View();
        }


        private void PopulateSections()
        {
            if (sectionHandler == null)
                sectionHandler = new SectionDataHandler();
            var sections = sectionHandler.GetSections();
            ViewData["SectionList"] = sections;
            ViewData["defaultSection"] = sections.First();
        }

        public ActionResult ViewTransactions()
        {
            return View();
        }

        #endregion

        public ActionResult Cart_Read([DataSourceRequest] DataSourceRequest request)
        {

            CartHandler ch = new CartHandler();
            string sql = @"      select c.CartId, p.ProductName, ci.Quantity, ci.Price, ci.Quantity * ci.Price as Total, c.DateCreated, c.CheckedOut
                    from dbo.Cart c
                    inner join dbo.CartItems ci on c.CartId = ci.CartId
                    inner join amz.Products p on ci.ProductId = p.ProductID
                    order by DateCreated, CheckedOut
              ";
            var result = ch.GetCartView(sql);

            return Json(result.ToDataSourceResult(request));
        }



        public ActionResult Editing_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(productHandler.GetProducts(null,null,true).ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Editing_Create([DataSourceRequest] DataSourceRequest request, AmzProduct product)
        {

            var addedProduct = productHandler.AddProduct(product);
            if (addedProduct != null)
            {
                ViewBag.Message = "Record saved";
                ViewBag.ErrorFound = false;

                product.ProductID = addedProduct.ProductID;
            }
            else
            {
                ViewBag.Message = "Failed to save record";
                ViewBag.ErrorFound = true;

            }


            return Json(new[] { product }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Editing_Update([DataSourceRequest] DataSourceRequest request, AmzProduct product)
        {
            productHandler.UpdateProduct(product);

            return Json(new[] { product }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Editing_Destroy([DataSourceRequest] DataSourceRequest request, AmzProduct product)
        {
            string destinationFilePath = System.Web.HttpContext.Current.Server.MapPath("~/Content/products");
                    
                try
                {
                    string fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.OriginalImageId);
                    FileInfo fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try
                        {
                            fi.Delete();
                        }
                        catch { }
                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.SmallImageId);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }
                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.MediumImageId);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }
                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.LargeImageId);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }
                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdOne);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }

                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdTwo);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }
                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdThree);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }
                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdFour);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }
                    }
                    fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdFive);
                    fi = new FileInfo(fileToDelete);
                    if (fi.Exists)
                    {
                        try {
                            fi.Delete();
                        }
                        catch { }
                    }



                }
                catch (Exception ex)
                {
                    logger.Fatal(ex);
                }


                productHandler.DeleteProduct(product);

            return Json(new[] { product }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult UploadImage(IEnumerable<HttpPostedFileBase> files, int productID)
        {
            string uploadMessage = FILE_UPLOAD_SUCCESSFUL;
            bool fileUploadFailed = false;
            bool fileIsValid = true;
            try
            {
                var request = System.Web.HttpContext.Current.Request;

                if (productID == 0)
                {
                    uploadMessage = "Can't except product id 0. Add a product -> Save Changes -> Select the row -> Upload image";
                    fileIsValid = false;
                    fileUploadFailed = true;
                }

                var product = productHandler.GetProduct(productID);

AmzWholeSaleWeb/AmzWholeSaleWeb/Views/Shared/AmzWholeSale/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendo")
    @Scripts.Render("~/bundles/simplex")
    @RenderSection("scripts", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/kendo/css")
    @Styles.Render("~/Content/amzwholesale/Site.css")
    @*<script src="@Url.Content("~/Scripts/kendo/kendo.all.min.js")" type="text/javascript"></script>*@
    <script>
        /*    Section Data */
        function SectionListDataBound() {
            this.value('Prime');
        }

    </script>

</head>
<body>
    <style>
        .cart {
            text-align: right;
            vertical-align:text-top;
            font-weight: bold;
            font-size: 10px;
            color: black;
            background-color:lightgray;
            text-decoration: underline;
            line-height: 5px;
            margin-right:5px;
            margin-bottom:5px;
            margin-left:0px;
            width:40px;
            /*display: inline-block;*/
            border:0;
            /*padding-bottom:15px;*/
        }

        .cartText {
            text-align: center;
            vertical-align:top;
            font-weight: bold;
            font-size: 14px;
            color: black;
            background-color:lightgray;
            text-decoration:none;
            line-height: 5px;
            margin-right:0px;
            padding-bottom:0px;
            min-width:10px;
            border:0;
            padding-bottom:5px;
        }

        .search-bar {
            padding-bottom: 2px;
            padding-right: 2px;
            float: left;
        }

        .cartButton{
            border:1px solid #d1dcdf; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;font-size:12px;font-family:arial, helvetica, sans-serif; 
            padding: 10px 10px 10px 10px; 
            text-decoration:none; display:inline-block;text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; color: white;
            background-color: #f2f5f6; background-image: -webkit-gradient(linear, left top, left bottom, from(#f2f5f6), to(#c8d7dc));
            background-image: -webkit-linear-gradient(top, #f2f5f6, #c8d7dc);
            background-image: -moz-linear-gradient(top, #f2f5f6, #c8d7dc);
            background-image: -ms-linear-gradient(top, #f2f5f6, #c8d7dc);
            background-image: -o-linear-gradient(top, #f2f5f6, #c8d7dc);
            background-image: linear-gradient(to bottom, #f2f5f6, #c8d7dc);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#f2f5f6, endColorstr=#c8d7dc);
            margin-left:5px;
            max-height:52px;

        }


        .cartButton:hover{
             border:1px solid #b6c7cc;
             background-color: #d4dee1; background-image: -webkit-gradient(linear, left top, left bottom, from(#d4dee1), to(#a9c0c8));
             background-image: -webkit-linear-gradient(top, #d4dee1, #a9c0c8);
             background-image: -moz-linear-gradient(top, #d4dee1, #a9c0c8);
             background-image: -ms-linear-gradient(top, #d4dee1, #a9c0c8);
             background-image: -o-linear-gradient(top, #d4dee1, #a9c0c8);
             background-image: linear-gradient(to bottom, #d4dee1, #a9c0c8);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#d4dee1, endColorstr=#a9c0c8);
        }

        .payPal{
            padding-right:10px;
        }
        .resizedTextbox {
            min-width: 250px;
            min-height: 25px;
        }
    </style>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AMZ Wholesale", "Index", "AmzHome", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "AmzHome")</li>
                    <li>@Html.ActionLink("About", "About", "AmzHome")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "AmzHome")</li>
                    <li>@Html.ActionLink("Admin", "Index", "ProductAdmin")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
             <div class="navbar-collapse collapse">
                 <div class="search-bar">
                     @(Html.Kendo().DropDownList()
                          .Name("Section")
                          .DataTextField("SectionName")
                          .DataValueField("SectionName")
                          .Events(ev => ev.DataBound("SectionListDataBound"))
                          .DataSource(source =>
                          {
                              source.Read(read =>
                              {
                                  read.Action("GetSections", "Shared");
                              });
                          })
                          .HtmlAttributes(new { style = "width: 100px" })
                     )
                 </div>
                <div class="search-bar">
                    @*<input type="text"  class="k-textbox" name="nameSeartItems" id="idSearchItems" required="required" />*@
                    <input type="text" class="k-textbox resizedTextbox" name="nameSeartItems" id="idSearchItems" value="Search products" onfocus="if (this.value == 'Search products') { this.value = ''; }" />
                </div>
                <div class="search-bar">
                    @(Html.Kendo().Button()
                        .Name("searchProductButton")
                        .HtmlAttributes(new { type = "button" })
                        .ImageUrl(Url.Content("~/Content/shared/search.png"))
                        .Content(""))                
                </div>
                <div class="nav navbar-right">
                    <button id="idViewCart" class="cartButton"><div id="shoppingCartLink"> Cart</div>
                        <img src="~/Content/shared/cart.png" alt="Cart Icon" /> 
                    </button>
                </div>
                 <div class="nav navbar-right" >
                    <input id="idBuyNowTopMenu" type="image" name="submit" border="0"
                           src="https://www.paypalobjects.com/en_US/i/btn/x-click-but6.gif"
                           alt="PayPal - The safer, easier way to pay online">
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AMZ Wholesale    Contact us at 716 825 1744 | 716-825-1733</p>
        </footer>
    </div>
    
</body>
</html>