SportsNetwork/SportsNetworkWeb/Controllers/JobTicketController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SimplexInvoiceBL;
using SimplexInvoiceModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SimplexInvoiceWeb.Controllers
{
    public class TotalCharge
    {
        public decimal InputQuantity { get; set; }
        public decimal InputWeight { get; set; }
        public decimal InputBasePickupCharge { get; set; }
        public decimal InputMilage { get; set; }
        public decimal InputToll { get; set; }
        public decimal InputFuelSurcharge { get; set; }
        public decimal InputMiscCharges { get; set; }
        public string InputClient { get; set; }
        public decimal Charge { get; set; }

        public void Calc(decimal weightRate, decimal complimentaryWeight)
        {
            decimal weight = InputWeight - complimentaryWeight;
            if (weight < 0)
                weight = 0;

            Charge = weight * weightRate + InputBasePickupCharge + InputMilage + InputToll + InputFuelSurcharge + InputMiscCharges;
        }

    }

    public class JobTicketController : Controller
    {
        LogisticsCompanyHandler lch = new LogisticsCompanyHandler();
        ClientsCompanyHandler cch = new ClientsCompanyHandler();
        LogisticsCompany lc;
        JobTicketHandler jth = new JobTicketHandler();


        // GET: JobTicket
        public ActionResult Index(int? jobTicketId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            ViewData["JOB_TICKET_ID"] = jobTicketId;
            return View();
        }

        public ActionResult EditTicket(int jobTicketId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            return View();
        }


        public ActionResult SearchTicket()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            return View();
        }


        [HttpPost]
        public ActionResult CalcTotalCharge([DataSourceRequest]DataSourceRequest request, string inputChargeParameters)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var json_serializer = new JavaScriptSerializer();
            TotalCharge chargeInput = json_serializer.Deserialize<TotalCharge>(inputChargeParameters);


            if (string.IsNullOrEmpty(chargeInput.InputClient))
                return Json(new { success = true, message = 0 }, JsonRequestBehavior.AllowGet);

            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);

            ClientCompany c = cch.GetClientCompanyByName(chargeInput.InputClient, lc);

            chargeInput.Calc(c.WeightRate, c.ComplimentaryWeight);
            
            


            //decimal totalCharges = inputQuantity * inputWeight * 

            return Json(new { success = true, message = chargeInput }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult SaveJobTicket([DataSourceRequest]DataSourceRequest request, string inputJobTicket)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var json_serializer = new JavaScriptSerializer();
            JobTicket ticket = json_serializer.Deserialize<JobTicket>(inputJobTicket);


            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);

            var clientCompany = cch.GetClientCompanyByName(ticket.ClientName, lc);
            ticket.ClientCompanyId = clientCompany.ClientCompanyId;


            PickupDeliveryAddress addrPickupFrom = new PickupDeliveryAddress(ticket.PickupFrom);
            PickupDeliveryAddress addrDeliverTo = new PickupDeliveryAddress(ticket.DeliverTo);

            PickupDeliveryAddress.Add(addrPickupFrom);
            PickupDeliveryAddress.Add(addrDeliverTo);


            if (ticket.JobTicketId == 0)
            {

                ticket.CreatedBy = User.Identity.Name;
                ticket.CompanyId = lc.CompanyId;
                
                ticket.JobTicketId = jth.Add(ticket, User.Identity.Name);
            }
            else
            {
                ticket.ModifiedBy = User.Identity.Name;
                jth.Update(ticket);

            }
            // Save to db here
            // Assign job ticket number to the object
            // return jobTicket

            return Json(new { success = true, message = ticket }, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public ActionResult GetClientDefaults([DataSourceRequest]DataSourceRequest request, string inputClient)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }


            if (string.IsNullOrEmpty(inputClient))
                return Json(new { success = true, message = 0 }, JsonRequestBehavior.AllowGet);

            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);

            ClientCompany c = cch.GetClientCompanyByName(inputClient, lc);

            

            return Json(new { success = true, message = c }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search_Read([DataSourceRequest] DataSourceRequest request, string jobDate, string clientName)
        {

            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);



            IEnumerable<JobTicket> result = jth.GetAllTickets(lc);
            if (result == null)
                result = new List<JobTicket>();

            if(!jobDate.Equals("UNSELECTED"))
            {
                result = result.Where(x => x.JobDate.ToString("d").Equals(jobDate));
            }

            if (!clientName.Equals("UNSELECTED"))
            {
                result = result.Where(x => x.ClientName.Equals(clientName));
            }


            return Json(result.ToDataSourceResult(request));
        }


        public ActionResult Editing_Read([DataSourceRequest] DataSourceRequest request)
        {

            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);



            IEnumerable<JobTicket> result = jth.GetTodaysTickes(lc);
            if (result == null)
                result = new List<JobTicket>();

            return Json(result.ToDataSourceResult(request));
        }

        [HttpGet]
        public ActionResult GetJobTicketInfo([DataSourceRequest]DataSourceRequest request, int jobTicketId)
        {

            
            return Json(new { success = true, message = jth.GetJobTicket(jobTicketId) }, JsonRequestBehavior.AllowGet);
        }



    }
}

SportsNetwork/SportsNetworkWeb/Controllers/MyClientsController.cs
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using log4net;
using SimplexInvoiceBL;
using SimplexInvoiceModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SimplexInvoiceWeb.Controllers
{
    public class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
    }

    public class ClientDDL
    {
        public string ClientName { get; set; }
        public int ClientID { get; set; }
    }
    public class MyClientsController : Controller
    {
        private static readonly ILog logger = LogManager.GetLogger(typeof(MyCompanyController));


        SimplexInvoiceHelper helper = new SimplexInvoiceHelper();
        LogisticsCompanyHandler lch = new LogisticsCompanyHandler();
        ClientsCompanyHandler cch = new ClientsCompanyHandler();
        LogisticsCompany lc;



        // GET: MyClients
        public ActionResult Index()
        {
            logger.Info("Simplex Invoice MyClients. Index()");

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            ClientCompany c = null;

            if (c == null)
            {
                c = new ClientCompany();
                c.CompanyName = string.Empty;
                c.ContactPerson = string.Empty;
                c.AddressLine1 = string.Empty;
                c.AddressLine2 = string.Empty;
                c.City = string.Empty;
                c.State = "NY";
                c.Zip = string.Empty;
                c.Email = string.Empty;
                c.MobileNumber = string.Empty;
                c.OfficeNumber = string.Empty;
                c.FaxNumber = string.Empty;
            }

            lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);
            if(lc != null)
            {
                c.WeightRate = lc.WeightRate;
                c.ComplimentaryWeight = lc.ComplimentaryWeight;
                c.BasePickupCharge = lc.BasePickupCharge;
            }


            ViewData["PU_FORM"] = c;

            return View();
        }

        [HttpPost]
        public ActionResult SaveClientInfo([DataSourceRequest]DataSourceRequest request, string clientCompanyString)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }


            string message = "Company saved.";
            var json_serializer = new JavaScriptSerializer();
           
            ClientCompany c = json_serializer.Deserialize<ClientCompany>(clientCompanyString);
            c.CreatedBy = User.Identity.Name;
            logger.InfoFormat("Saving company...");
            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);

            try
            {
                var existingCompany = cch.GetClientCompanyByName(c.CompanyName, lc);
                if (existingCompany == null)
                {
                    c.CompanyId = lc.CompanyId;
                    c.ClientCompanyId = cch.Add(c);
                }
                else
                {
                    c.CompanyId = existingCompany.CompanyId;
                    c.ClientCompanyId = existingCompany.ClientCompanyId;
                    logger.InfoFormat("Company exists. Updating client company.");
                    c.ModifiedBy = User.Identity.Name;
                    logger.InfoFormat("{0} rows updated.", cch.Update(c));
                }

                logger.InfoFormat("Company saved.");

            }
            catch (Exception ex)
            {
                message = string.Format("Failed to save company. Error: {0}", ex.Message);
                logger.Fatal(ex);
            }


            return Json(new { success = true, message = message }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetClientInfo([DataSourceRequest]DataSourceRequest request, string clientCompanyString)
        {

            
            string message = "Getting company";
            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);

            ClientCompany c = cch.GetClientCompanyByName(clientCompanyString,lc); 

            if (c == null)
            {
                c = new ClientCompany();
                c.CompanyName = clientCompanyString;
                c.ContactPerson = string.Empty;
                c.AddressLine1 = string.Empty;
                c.AddressLine2 = string.Empty;
                c.City = string.Empty;
                c.State = "NY";
                c.Zip = string.Empty;
                c.Email = string.Empty;
                c.MobileNumber = string.Empty;
                c.OfficeNumber = string.Empty;
                c.FaxNumber = string.Empty;
                c.WeightRate = 3;
                c.ComplimentaryWeight = 1000;
                c.BasePickupCharge = 56;

            }





            return Json(new { success = true, message = c }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Editing_Read([DataSourceRequest] DataSourceRequest request)
        {
            if (lc == null)
                lc = lch.GetCompanyRegisteredByUser(User.Identity.Name);



            IEnumerable<ClientCompany> result = cch.GetClientCompanies(lc.CompanyId);

            return Json(result.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Editing_Create([DataSourceRequest] DataSourceRequest request, ClientCompany company)
        {

            //var addedProduct = productHandler.AddProduct(product);
            //if (addedProduct != null)
            //{
            //    ViewBag.Message = "Record saved";
            //    ViewBag.ErrorFound = false;

            //    product.ProductID = addedProduct.ProductID;
            //}
            //else
            //{
            //    ViewBag.Message = "Failed to save record";
            //    ViewBag.ErrorFound = true;

            //}


            return Json(new[] { company }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Editing_Update([DataSourceRequest] DataSourceRequest request, ClientCompany company)
        {
            //productHandler.UpdateProduct(product);

            return Json(new[] { company }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Editing_Destroy([DataSourceRequest] DataSourceRequest request, ClientCompany company)
        {
            string destinationFilePath = System.Web.HttpContext.Current.Server.MapPath("~/Content/products");

            try
            {
                //string fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.OriginalImageId);
                //FileInfo fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }
                //}
                //fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.SmallImageId);
                //fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }
                //}
                //fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.MediumImageId);
                //fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }
                //}
                //fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.LargeImageId);
                //fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }
                //}
                //fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdOne);
                //fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }

                //}
                //fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdTwo);
                //fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }
                //}
                //fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdThree);
                //fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }
                //}
                //fileToDelete = string.Format(@"{0}\{1}", destinationFilePath, product.ImageIdFour);
                //fi = new FileInfo(fileToDelete);
                //if (fi.Exists)
                //{
                //    try
                //    {
                //        fi.Delete();
                //    }
                //    catch { }
                //}

SportsNetwork/SportsNetworkWeb/Views/Shared/AdminMenuHorizontal.cshtml
@(Html.Kendo().ToolBar()
    .Name("ToolBar")
    .Items(items =>
    {
        items.Add().Type(CommandType.Button).Togglable(true).Text("My Company").Id("btnMyCompany").Toggle("buttonToggleHandler");
        items.Add().Type(CommandType.Separator);
        items.Add().Type(CommandType.Button).Togglable(true).Text("My Clients").Id("btnMyClients").Toggle("buttonToggleHandler");
        items.Add().Type(CommandType.Button).Togglable(true).Text("Invoices").Id("btnInvoices").Toggle("buttonToggleHandler");
        items.Add().Type(CommandType.Separator);
    })
    .Events(e => e.Click("onClick").Toggle("onToggle").Open("onOpen").Close("onClose").OverflowOpen("onOverflowOpen").OverflowClose("onOverflowClose"))
)
@*<div class="navbar-collapse collapse">
        <div style="float: left; width: 100px;">@Html.ActionLink("Add", "Index", "ProductAdmin", routeValues: null, htmlAttributes: new { id = "registerLink" })</div>
        <div style="float: left; width: 100px;">@Html.ActionLink("Manage", "ManageProduct", "ProductAdmin", routeValues: null, htmlAttributes: new { id = "loginLink" })</div>
        <div style="float: left; width: 100px;">@Html.ActionLink("ViewTransactions", "ViewTransactions", "ProductAdmin", routeValues: null, htmlAttributes: new { id = "loginLink" })</div>
        <div style="width: 100px;">@Html.ActionLink("App Data", "Index", "ReferenceData", routeValues: null, htmlAttributes: new { id = "loginLink" })</div>
        <br style="clear: left;" />
    </div>*@

<script>

    function buttonClickHandler(e) {
        //alert(e.target.text() + " 'click' event is fired.");
        if (e.target.text() == "My Company") {
            var url = '@Url.Action("Index", "MyCompany")';
            window.location.href = url;
        }

    }

    function buttonToggleHandler(e) {
        //alert(e.target.text() + " 'toggle' event is fired.");

        if (e.target.text() == "Invoices") {
            var url = '@Url.Action("Index", "Invoices")';
            window.location.href = url;
        }
        if (e.target.text() == "App Data") {
            var url = '@Url.Action("Index", "ReferenceData")';
            window.location.href = url;
        }
        if (e.target.text() == "My Clients") {
            var url = '@Url.Action("Index", "MyClients")';
            window.location.href = url;
        }
        if (e.target.text() == "My Company") {
            var url = '@Url.Action("Index", "MyCompany")';
            window.location.href = url;
        }

    }

    function splitButtonClickHandler(e) {
        alert("SplitButton event: " + e.id + " is clicked.");
    }

    function onClick(e) {
        //alert("ToolBar 'click' event is fired for element with id: " + e.id);
    }

    function onToggle(e) {
        //if (e.group == "radio") {
        //    alert("Toolbar 'toggle' event: " + e.id + " button is selected from group: " + e.group);
        //} else {
        //    alert("ToolBar 'toggle' event: " + e.id + " button is changed");
        //}
    }

    function onOverflowOpen(e) {
        alert("Overflow container open");
    }

    function onOverflowClose(e) {
        alert("Overflow container close");
    }

    function onOpen(e) {
        alert("SplitButton popup open");
    }

    function onClose(e) {
        alert("SplitButton popup close");
    }


</script>

SportsNetwork/SportsNetworkWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/Scripts/sports.network.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/kendo/css")

</head>

<body>
    <style>
        .pageFooterTableCell {
            min-width: 200px;
            max-width: 200px;
            display: table-cell;
            border: 0;
        }
    </style>
    <div id="navBar" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SIMPLEX INVOICE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Invoices", "Index", "Invoices")</li>
                    <li>@Html.ActionLink("Job Ticket", "Index", "JobTicket")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
            <div style="max-height:5px;">
                @Html.Partial("_MainMenu")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div id="footer" class="container page-footer">
        <footer>
            <b>Simplex Sys Inc.</b>  14 Fountain Lane Jericho, NY- 11753 Phone: 516 639 8131 Email: sales@simplexsys.co<br />
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

SportsNetwork/SportsNetworkWeb/Views/Shared/_MainMenu.cshtml
<div id="megaStore">
    @(Html.Kendo().Menu()
      .Name("Menu")
      .Items(items =>
      {
          items.Add()
                  .Text("Manage League")
                  .Items(children =>
                  {
                      children.Add().Text("Leagues").Action("CreateLeague", "TennisNetwork");
                      children.Add().Text("Players").Action("CreatePlayer", "TennisNetwork");
                      children.Add().Text("Add Players To League").Action("AddPlayerToLeague", "TennisNetwork");
                      //children.Add().Text("Manage Ticket")
                      //            .Items(innerChildren =>
                      //            {
                      //                innerChildren.Add().Text("New Ticket").Action("Index","JobTicket");
                      //                innerChildren.Add().Text("Today's tickets").Action("Index","JobTicket");
                      //                innerChildren.Add().Text("Search Tickets").Action("SearchTicket","JobTicket");
                      //                innerChildren.Add().Text("Ticket Summary").Action("Index","Home");
                      //            });

                  });

          items.Add()
                 .Text("Schedule Games")
                 .Items(children =>
                 {
                     children.Add().Text("Let's Play").Action("LetsPlay", "TennisNetwork");
                     children.Add().Text("My Profile").Action("AddProfile", "TennisNetwork");
                     children.Add().Text("Schedule Singles").Action("ScheduleSinglesGame","TennisNetwork");
                     children.Add().Text("Schedule Doubles").Action("ScheduleDoublesGame", "TennisNetwork");
                     //children.Add().Text("Schedule Singles")
                     //            .Items(innerChildren =>
                     //            {
                     //                innerChildren.Add().Text("Unpaid Invoices");
                     //                innerChildren.Add().Text("Search Invoice");
                     //            });

                 });

          items.Add()
                .Text("Admin")
                .Items(children =>
                {
                    children.Add().Text("Locations").Action("CreateLocation", "TennisNetwork");

                });

      })
    )

</div>
<style>
   
    #megaStore {
        /*max-width: 600px;*/
        margin: 0px auto;
        padding-top: 0px;
        /*background: url('../../content/web/menu/header.jpg') no-repeat center 0;*/
    }

    .k-menu
    {
        border:0px;

            /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#e4efc0+0,abbd73+100;Olive+3D+%232 */
        background: rgb(228,239,192); /* Old browsers */
        background: -moz-linear-gradient(top,  rgba(228,239,192,1) 0%, rgba(171,189,115,1) 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top,  rgba(228,239,192,1) 0%,rgba(171,189,115,1) 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom,  rgba(228,239,192,1) 0%,rgba(171,189,115,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e4efc0', endColorstr='#abbd73',GradientType=0 ); /* IE6-9 */

    }
    
    .k-menu .k-link 
    {
        font-size:11px;
        text-decoration:none;
        font-weight:bold;
        border:0px;
    }

</style>